"""empty message

Revision ID: 3656e5bfb6b4
Revises: 600ee30f90ca
Create Date: 2019-04-30 22:25:00.905257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3656e5bfb6b4'
down_revision = '600ee30f90ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_owner')
    # ### end Alembic commands ###
